module.exports = {
  boolean: require("./src/arr/boolean.js"),
  coin: require("./src/arr/coin.js"),
  falsy: require("./src/arr/falsy.js"),
  isEmail: require("./src/checker/isEmail.js"),
  isNumber: require("./src/checker/isNumber.js"),
  isInstagramUrl: require("./src/checker/isInstagramUrl.js"),
  isYoutubeUrl: require("./src/checker/isYoutubeUrl.js"),
  isSoundcloudUrl: require("./src/checker/isSoundcloudUrl.js"),
  isString: require("./src/checker/isString.js"),
  isURL: require("./src/checker/isUrl.js"),
  magicConchShell: require("./src/arr/magicconchshell.js"),
  makeId: require("./src/string/makeid.js"),
  makeidNumber: require("./src/string/makeidnumber.js"),
  minMax: require("./src/another tools/min-max.js"),
  option: require("./src/arr/options.js"),
  passGen: require("./src/string/password-gen.js"),
  randomArr: require("./src/arr/random-arr.js"),
  randomString: require("./src/string/random-string.js"),
  rps: require("./src/arr/rps.js"),
  shuffle: require("./src/arr/shuffle.js"),
  userAgents: require("./src/arr/random-user-agents.js"),
  yesNo: require("./src/arr/yesno.js"),
};
