module.exports = {
  boolean: require("./src/arr/boolean.js"),
  isEmail: require("./src/checker/isEmail.js"),
  isNumber: require("./src/checker/isNumber.js"),
  isString: require("./src/checker/isString.js"),
  isURL: require("./src/checker/isUrl.js"),
  makeId: require("./src/string/makeid.js"),
  minMax: require("./src/another tools/min-max.js"),
  option: require("./src/arr/options.js"),
  passGen: require("./src/string/password-gen.js"),
  randomArr: require("./src/arr/random-arr.js"),
  randomString: require("./src/string/random-string.js"),
  rps: require("./src/arr/rps.js"),
  userAgents: require("./src/arr/random-user-agents.js"),
  yesNo: require("./src/arr/yesno.js"),
};